### ISSUE TITLE
Ambiguities that arose from the test cases

### ISSUE THREAD

**Issue by Lyxal** [Vyxal/Vyxal#1164]
Round 2 of everyone's favourite game. This time, the failed tests are to do with decisions regarding things like typing or edge cases that weren't previously thought of. That means that some things can be ignored/left as-is.

- [x] `½`: `[""] -> ["", ""]` (what to do with empty string?) (#1168)
- [x] `F`: `["12345",["2","4","5"]] : "13"` (should lhs be converted to list if rhs is already list?) (#1169)
- [x] `O`: `[1213121, "1"] : 4` (should string be considered same as int?) (#1170)
- [x] `U`: `["1",1] : ["1",1]` <s>(should `"1"` and `1` be considered equal in this context?)</s> Someone forgot to format the test correctly.
- [x] `V`: `[234,"2",4] : 234` (should `"2"` and `2` be considered equal in this context?) (#1171)
- [x] `ḭ`: `["a",3] : ""` <s>(Why wouldn't it be `["a"]`?) (#1172)</s> Looks like it's valid after all
- [x] `Ȧ`: `[[], [1, 2], 2] : [2, 2]` (What even _should_ happen here? What does assigning to an empty list do?) (#1173)
- [x] `İ`: `[[1,2,3], [-1,0.1,1.9,"0"]] : [3,1,2,1]` (That's a tricky one. What if there's a string in the index list?) (#1298)
- [x] `Ṁ`: `[134,1,2] : 1234` (Should the result be a list or a number? What if it was `"a"` instead of `2`?)
- [x] `Ẋ`: `[12,34] : [13,14,23,24]` (Should those be numbers or lists?)
- [x] `Ẏ`: `[123,2] : 12` (Number or list?) (#1199)
- [x] `Ż`: `[123,3] : 23` (Same as above) (#1199)
- [x] `⌊`: `["-123"] : -123` (Should `-` be counted as part of the number?) (#1198)
- [x] `∪`: `["12",12] : ["1","2"]` (How should strings and numbers interplay here?) (#1299)
- [x] `Ǒ`: `[1.125, 2] : -3` and `[1.125, 3] : 2` <s>(What rules for divisibility did you use? /srs is there a way of determining decimal divisibility?)</s> I think integer order is fine here. (#1301)
- [x] `øḞ`: `["234",2,4] : "234"` <s>(Depends on how strings + numbers should interact)</s> current behaviour is fine. (#1312)
- [x] `øṄ`: `[234,"2",4,1]` <s>(Same as above)</s> same as above (#1313)
- [x] `ÞS`: `[123] : [1,12,2,123,23,3]` (Lists or numbers?) (#1297)
- [x] `Þ∨`: `[1234,"13"] : [2,4]` <s>(yet another query about type interaction)</s> It needed some attention anyway (#1314)
- [x] `Þ∩`: (will be the same as above) (#1316)
- [x] `Þ∪`: (this one too) (#1317)
- [x] `Þ⊍`: (and this one) (#1318)
- [x] `ÞK`: `[123456] : [123456, 23456, 3456, 456, 56, 6]` (should those be numbers or lists?) (#1303)

**Comment by Lyxal** [comment]
From Seggan:

![image](https://user-images.githubusercontent.com/36217120/175548805-5ca12485-5f87-408e-8ce5-0e6303de4eab.png)

**Comment by Lyxal** [comment]
From emanresuA:

![image](https://user-images.githubusercontent.com/36217120/175548890-475ac137-bc15-4498-bf56-49a17b88c521.png)

**Comment by Steffan153** [comment]
My opinions:
- `½`: yes: two strings means `["", ""]`
- `F`: yes: lhs is string, so keep a string
- `O`: yes
- `V`: no: should be `434` (as a number, not a string like it currently is)
- `ḭ`: no: should be `"a"`
- `Ȧ`: yes: this is perfectly clear to me, assigning to a non-existent index means just append normally
- `İ`: no: it should treat the first list as indices: `[0.1, 1.9, "0"]`
- `Ṁ`: yes: all inputs were numbers, so keep it a number
- `Ẋ`: no: make them lists
- `Ẏ`: yes: keep it a number
- `Ż`: yes: keep it a number
- `⌊`: yes
- `∪`: no: different types should be treated differently, so `['1', '2', 1, 2]`
- `Ǒ`: no: those should return 0, I don't understand how `-3` and `2` were calculated
I'll do the digraphs later.

**Comment by cgccuser** [comment]
- `½`: `[""] -> ["", ""]` is fine. For every other input, `½` outputs a list of length 2, so why not for `""` too?
- `F`: `["12345",["2","4","5"]] : [1,3]`. I think lhs should be converted to a list. If someone wanted the result to be a string, they can join rhs on `""`.
- `O`: `[1213121, "1"] : 0`. I don't think strings should be treated the same as numbers.

- `Ẋ`: `[12,34] : cartesian(range(12), range(34))`. I think there are fewer situations where it would be useful to do the cartesian product of the digits and turn them back into numbers. On the other hand, I've needed cartesian products of ranges in the past.
- `Ẏ`: `[123,2] : 12`. Despite what I said for `Ẋ`, here, it'd be useless to do `range(123)[:2]` because you could just do `range(2)` instead. If you have numbers as digits set, it wouldn't be useless to get the list `[1,2]`, but I think people would usually want `12` instead. If they really do want the list `[1,2]`, that's fine because it would get likely get implicitly converted into that list while going through a later element anyway.
- `Ż`: `[123,3] : 23`. This should be consistent with `Ẏ`'s behavior.
- `⌊`: `["-123"] : -123`. Yes, `-` should be counted as part of the integer. After all, it's "integer," not "natural number."
- `∪`: `["12",12] : ["12",1,2] or ["12",1,2,3,...,12]` depending on whether you've set the `R` flag (btw, I dislike the character `∪`, it looks just like `U`)
