### ISSUE TITLE
2.6 Release Checklist

### ISSUE THREAD

**Issue by Lyxal** [Vyxal/Vyxal#273]
- [x] Flags implemented (existing and from #160)
- [x] Server working
- [x] Auto-integration to PA
- [x] Better permalink encoding #237

**Comment by pxeger** [comment]
Can I work on auto-integration?

**Comment by Lyxal** [comment]
Yes please do
